### ISSUE TITLE
Opens in browser rather than zeal

### ISSUE THREAD

**Issue by abers** [Kwaadpepper/zealdoc#1]
When running a search it opens a new browser tab rather than Zeal. Looking at the URI it looks like the `:` is missing after dash-plugin:

`dash-plugin//keys=`

when it should be:

`dash-plugin://keys=`

Edit: I'm on Ubuntu 20.04 with i3-gaps as my window manager.

**Comment by Kwaadpepper** [comment]
In the code the link is correct.
https://github.com/Kwaadpepper/zealdoc/blob/7af783b51726e4f16e0a723a97be0ba023ac9977/lib/result_items.py#L42

I don't have much time to investigate this. I'll try to see if I can reproduce this, later. Thank you for reporting.

**Comment by zany130** [comment]
same issue here on arch Linux KDE

**Comment by ZarthKa** [comment]
same issue here on manjaro Linux KDE

It opens Firefox with URL `http://dash-plugin//keys=python&query=string` when I do like the gif on this Page

**Comment by Kwaadpepper** [comment]
I had a quick look over it.
It internally uses ```xdg-open```

So for example if you type in console ```xdg-open "dash-plugin://keys=python,django&query=string&query=toto"``` and it open the web browser it means you may not have zeal installed correctly.

For example on Ubuntu I have 

in ```/usr/share/applications/org.zealdocs.Zeal.desktop ```

      [Desktop Entry]
      Version=1.0
      Name=Zeal
      GenericName=Documentation Browser
      Comment=Simple API documentation browser
      Exec=zeal %u
      Icon=zeal
      Terminal=false
      Type=Application
      Categories=Development;
      MimeType=x-scheme-handler/dash;x-scheme-handler/dash-plugin;

As you can see on the last line it register itself as handling ```dash-plugin://``` urls. So may be the zeal package installed on your distro is wrong. You may test this.

**Comment by ZarthKa** [comment]
```

[karsten@ktsn13 ~]$ which zeal
/usr/bin/zeal
[karsten@ktsn13 ~]$ which xdg-open
/usr/bin/xdg-open
[karsten@ktsn13 ~]$ cat /usr/share/applications/org.zealdocs.zeal.desktop
[Desktop Entry]
Version=1.0
Name=Zeal
GenericName=Documentation Browser
Comment=Simple API documentation browser
Exec=zeal %u
Icon=zeal
Terminal=false
Type=Application
Categories=Development;
MimeType=x-scheme-handler/dash;x-scheme-handler/dash-plugin;
StartupWMClass=Zeal
```
well, my last line is `StartupWMClass=Zeal`, but despite of that there seems to be no difference....

**Comment by Kwaadpepper** [comment]
Could you try this ? Copy/paste everything

`xdg-open "dash-plugin://keys=python,django&query=string&query=toto"`


Xdg-open should be aware that zeal can handle dash-plugins uri, so that's the test.

**Comment by ZarthKa** [comment]
It opens `http://dash-plugin//keys=python,django&query=string&query=toto` in the browser (Firefox in my case).

Anyways, I came across a rather old [discussion](https://github.com/blakeembrey/atom-dash/pull/31) (please, tell me if it has nothing to do with the actual issue), where #dirtyvader commented on 14 Jan 2016

> In fact actually, the problem is not due to xdg-open itself. When xdg-open is execute in a desktop environment, like KDE or Gnome, it delegate the opening to this desktop environment. In the case of KDE, it's kioclient, which accept to open the dash-plugin URI scheme only if you have added a new mime type (like application/zeal or so), register a new protocol handler and call kioclient like this :

> kioclient execute dash-plugin://query=.SetFlags application/zeal"

Eventualy I came to enter `kioclient5 openProperties "dash-plugin://keys=python&query=string&query=toto"` and that opened a window I cannot really cope with.

Something, about "create new filetype"

I think this is the wrong way to do it, isn't it?

**Comment by Kwaadpepper** [comment]
I found this https://github.com/zealdocs/zeal/issues/471, so you may have pointed something that could help to sort out this

Could you try this ?
```xdg-open "dash-plugin:keys=python&query=string"```

**Comment by Kwaadpepper** [comment]
The final thing is https://github.com/blakeembrey/atom-dash/issues/37#issuecomment-237140968
I will test something. In the week. And update the plugin accordingly

**Comment by ZarthKa** [comment]
Didn't I answer this request?

> Could you try this ?
> xdg-open "dash-plugin:keys=python&query=string"

Oh my, my fault...

this works absolutely.
