### ISSUE TITLE
Initial error

### ISSUE THREAD

**Issue by 7system7** [Kwaadpepper/zealdoc#2]
Firstly. thank you for your work. I have got this error initially

```
2023-10-28 12:47:42,550 | ERROR | Zealdoc |-> [Errno 2] No such file or directory: 'Zeal/Zeal/docsets'
com.github.kwaadpepper.zealdoc | 2023-10-28 12:47:42,550 | ERROR | Zealdoc: log() | [Errno 2] No such file or directory: 'Zeal/Zeal/docsets'
```

And the plugin does not work. What have I wrong?

**Comment by Kwaadpepper** [comment]
It's been years since I haven't use Ulauncher.
In order to work you may have Zeal installed and downloaded some docs using Zeal. 
Is it the case ?
You could check. The directory where docs are downloaded?

**Comment by 7system7** [comment]
Ah, yes. Thank you. After I installed it, then started working.
